services:
  - type: web
    name: bytebeat
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ByteBeat:app
    env: static
    healthCheckPath: /healthcheck
    routes:
      - path: /
        targetService: main.html
      - path: /articles
        targetService: articles.html
      - path: /saved
        targetService: saved.html
