# create a new static service to run ByteBeat.py
services:

- type: web
  name: bytebeat
  env: static
  buildCommand: python3 ByteBeat.py
  staticPublishPath: ./build
  pullRequestPreviewsEnabled: true # optional
  buildFilter:
    paths:
    - src/**/*.js
    ignoredPaths:
    - src/**/*.test.js
  headers:
    - path: /*
      name: X-Frame-Options
      value: sameorigin
  routes:
    - type: redirect
      source: /old
      destination: /new
    - type: rewrite
      source: /a/*
      destination: /a